### ISSUE TITLE
HR composite metrics are missing

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/mesh-observability#73]
I deployed the composites for employee portal with hr, stock, and employee from - https://github.com/wso2-cellery/sdk/tree/master/test-cases/composite.

I could see all metrics but the hr metrics is empty. 
<img width="1507" alt="Screen Shot 2019-09-25 at 11 41 44 AM" src="https://user-images.githubusercontent.com/7677649/65574794-0099b680-df8c-11e9-94c7-0c9ec0225d00.png">

**Comment by sinthuja** [comment]
@HasithaAthukorala , please look into this with nadun.

**Comment by nadundesilva** [comment]
It seems like now Istio simply sends "unknown" as the sourceUID for any pod without a sidecar. Before we got the value of the user agent header when a sidecar received an request from the global gateway.

Therefore, we may not be able to show the global gateway in any views in the dashboard. I will look into getting the metrics in the list view.

**Comment by nadundesilva** [comment]
The actual issue was due to an inner join we were performing before. I updated the whole flow to use Istio telemetry data completely. This removed multiple Siddhi level stream joins and also allows us to remove an inMemory topic we are using. This also fixes this issue as well.
